[project]
name = "transformer-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.12.0",
    "ipykernel>=7.1.0",
    "numpy>=2.3.4",
    "torch>=2.9.0",
    "transformers>=4.57.3",
]
