[project]
name = "attention-skipping"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lighteval>=0.13.0",
    "torch>=2.9.1",
    "transformers>=4.57.3",
]
